name: Bed-PVP
version: '${version}'
main: com.john.bedpvp.Bed_PVP
api-version: '1.20'
commands:
  bed-pvp:
    description: Main command
    usage: /bed-pvp
  bed-pvp-start:
    description: Start the game
    usage: /bed-pvp-start
    permission: bed-pvp.start
    default: op
  bed-pvp-stop:
    description: Stop the game
    usage: /bed-pvp-stop
    permission: bed-pvp.stop
    default: op
